import {Inter} from 'next/font/google'
import './globals.css'
import QueryProvider from "./QueryProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Doc'care",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  )
}
